Set<String> fruits  =  new set<string>();
fruits.add('pineaple');
fruits.add('apple');
fruits.add('grapes');
fruits.add('pineaple');
system.debug(fruits);

list<string> shoppinglist = new list<string>();
shoppingList.add('camera');
shoppingList.add('clothes');
system.debug(shoppinglist);
set<string> shopNow = new set<string>();
shopNow.addAll(shoppingList);
system.debug(shopNow);

set<integer> s = new set<integer>{1,2,3,4,5};
s.add(999);
system.debug(s);
