import { createElement } from 'lwc';
import DataBinding3EnginyutubeAtrriubte from 'c/dataBinding3EnginyutubeAtrriubte';

describe('c-data-binding3-enginyutube-atrriubte', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-data-binding3-enginyutube-atrriubte', {
            is: DataBinding3EnginyutubeAtrriubte
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});