public class Casetrigger3handler {
   
   
   public static integer counnTriggerExc=0;
   
   public static integer countRecordsUpdated=0;
   
   public static set<string> setAllSubject = new set<string>();
   public static list<case> allRecords = new list<case>();
   
   
   
   
   
   
   
   
   
   
    /*public static integer countTriggerExecution = 0;
    public static integer countrecordsUpdate = 0;
    public static set<string> setallSubject = new set<string>();//clasa aid sifirlanmiyo..
    public static list<case> allRecords = new list<case>();*/




}
