public  class own {
    public void own() {
String firstName = 'Hiji';
String lastName = 'Hajiyeva';
String fullName = firstName + ' ' + lastName;
System.debug(fullName);

System.debug(2==2 && 1>2 );
System.debug(2==2 && 1!=2 );
System.debug(2==3 && 10>2 );
System.debug(3<2 && 1>2 );


System.debug(2==2 ||1>2 );
System.debug(2==2 || 1!=2 );
System.debug(2==3 && 10>2 );
System.debug(3<2 || 1>2 );
Integer num1 = 12;
Integer num2 = 8;
Integer sum = num1 + num2;
System.debug('Sum: ' + sum);

    }
}


