public  class Practise12 {
      public static list<ogrenci12> studentList = new list<ogrenci12>();
public static void students(){

    Ogrenci12 ss1 = new Ogrenci12('Esma','Toprak','10B',false);
    system.debug(ss1);
    Ogrenci12 ss2 = new Ogrenci12('Hijran','Toprak','11B',false);
    system.debug(ss2);

    Ogrenci12 ss3 = new Ogrenci12('Tolga','Toprak','9C',true);
    system.debug(ss3);



    //Ogrenci12 s = new Ogrenci12();


}
    }
