public class primitiveDataTypesDemo {

public void printBasicDataType(){
    system.debug('printing data types');
    system.debug('datatypes two');
string batchName  = 'Batch 12';
integer totalCandidates = 65;
boolean isAdminCompleted = true;
system.debug('Batchname is...' + batchName);
system.debug('total Candidates is...' + totalCandidates);
system.debug('is admin completed is...' + isAdminCompleted);
Decimal decValue = 28.1;
System.debug('Decimal:' + decvalue);
Long longValue = 2147483648L;
System.debug('Longvalue:' + longValue);




}

}
