public class SalesforceDeveloper {
    public void myFirstCode() {
string myFavouriteCity = 'Paris';
string myFavouriteFilm = ' Harry Potter';
string myFavouriteSeason = 'Summer';
system.debug(myFavouriteCity);
System.debug(myFavouriteFilm);
System.debug(myFavouriteSeason);

}
public void myFavourite(){
string myFavouriteCity2 = 'Toronto';
integer myFavNum = 8;
integer myFavNum2 = 10;
system.debug('My favourite city is: ==> ' + myFavouriteCity2);
system.debug('My Favourite number is: ' + myFavNum);
system.debug('My fav number is: ' + myFavNum2);


}

}
