public  class studentdetails {
    public void NameofStudent() {
system.debug('Hijran');
string fname = 'hijran';
System.debug('Name: ' +fname);
string area = 'Baku';
system.debug('Place of born: ' + area);
string hobbies = 'Coding,walking,riding a bike,travel';
system.debug('Things I like: ' + hobbies);
object travel = 'Turkey,Paris,New York,Mayami ';
system.debug('Place to visit: ' + travel);
    }
}
